### ISSUE TITLE
Getting ambiguous errors messages

### ISSUE THREAD

**Issue by henrytseng** [alivecor/simple_hl7#3]
I received some ambiguous error messages:

```
undefined method `gsub!' for #<SimpleHL7::Field:0x007fa9b708bae8>
```

Can we update some of these methods so that debugging will move smoother?

**Comment by henrytseng** [comment]
Happy to do a pull request

**Comment by hportlock** [comment]
Thanks for the pull request, though could you clarify how you got the original error message?

I'm a little hesitant to swallow any StandardError that is thrown and replace it with an ArgumentError.

**Comment by henrytseng** [comment]
Okay changed that to StandardError.  Ideally, a new error type should be created.

**Comment by hportlock** [comment]
Oh, sorry I think I was unclear. My concern is that by doing this:
```ruby
rescue => e
```
You're capturing any instance of StandardError that is thrown in the message body, but since the new error you're raising doesn't use the error you caught you'd be loosing the context of the original error which could also be useful in debugging.

What if it was something like this instead:
```ruby
rescue => e
  raise e, "Encountered exception building message: #{e}", e.backtrace
end
``` 
That way we could preserve the original exception with the backtrace and also add extra context. How's that sound?

**Comment by henrytseng** [comment]
Ah.  I was thinking of fixing something more along the lines of 

```
seg[3] = SimpleHL7::Field.new()
```

Throwing an error since it's still valid, though you intend for people to use

```
seg.set_subcomposite(9, field)
```

It's not a big deal but I imagine that errors thrown from Subcomponent would be more informative if it showed them *what* threw the error because it's recursive it'd be difficult to find out unless if someone read the code.  Re-raising the error would be helpful.  

I think this PR is more along the lines of what we're looking for?  Correct me if I am wrong.  

https://github.com/alivecor/simple_hl7/pull/4

**Comment by hportlock** [comment]
Ah, gotcha. Yeah this PR looks good. I agree too, in the future it might also be helpful for the setter to throw an error if the object is invalid. I can see how that might be confusing.

I'll merge your PR and make a new build soon. Thanks a bunch!
